name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Print DockerHub image reference
        run: echo "Using image: ${{ secrets.DOCKERHUB_USERNAME }}/fruits-api:latest"

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fruits-api:latest

      - name: Show Docker images (sanity check)
        run: |
          docker images | grep fruits-api || echo "No image found"

      - name: Stop & remove any existing container
        run: |
          docker stop fruits-api || true
          docker rm fruits-api || true

      - name: Run Docker container (detached mode)
        run: |
          set -e
          docker run -d --name fruits-api -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/fruits-api:latest

      - name: Show running containers (confirm success)
        run: docker ps | grep fruits-api || echo "❌ Container did not start"

