name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Set lowercase DockerHub username
      run: echo "DOCKER_USER=$(echo '${{ secrets.DOCKERHUB_USERNAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Pull Docker Image
      run: |
        docker pull ${DOCKER_USER}/fruits-api:latest

    - name: Stop existing container (if running)
      run: |
        docker stop fruits-api || true
        docker rm fruits-api || true

    - name: Run Docker Container on Port 8000
      run: |
        docker run -d --name fruits-api -p 8000:8000 \
          ${DOCKER_USER}/fruits-api:latest





























































